### ISSUE TITLE
Unnecessary scrollbar due to 100vw

### ISSUE THREAD

**Issue by simevidas** [paigen11/paigeniedringhaus.com#1]
When the browser has classic scrollbars (e.g., on Windows), your website shows an unnecessary scrollbar. Please take a look at the video below.

This issue is caused by the CSS value `100vw`.

> The CSS length value `100vw` is equal to the width of the `<html>` element. However, if a classic vertical scrollbar is added to the page, the `<html>` element becomes narrower (as explained above), but `100vw` stays the same. In other words, `100vw` is wider than the page when a classic vertical scrollbar is present.

https://css-tricks.com/weekly-platform-news-reduced-motion-cors-whitehouse-gov-popups-and-100vw/#the-css-100vw-value-can-cause-a-useless-horizontal-scrollbar

https://user-images.githubusercontent.com/716405/129596937-0ffa03f3-26b8-4452-a5f0-de5cc0c9e62c.mov

**Comment by paigen11** [comment]
Thanks for reporting this - and apologies for not seeing it sooner. I will fix this now. :)
